SMU- Computer Engineering 3학년 2019243064 박규민

In [256]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#하단 문장이 분류 평가 모듈입니다.
from sklearn.metrics import accuracy_score, precision_score, recall_score , f1_score, roc_auc_score

In [257]:
#과제에서 지정해준 csv파일을 불러옵니다.(저는 JupyterLab으로 진행하였어서 경로가 타 SW와 다를 수 있습니다)
df = pd.read_csv('./Glioblastoma.csv', sep = ',', header = None)

#0번째 행을 속성값으로 지정
df = df.rename(columns=df.iloc[0])

#컬럼 명 지정되어있으니 0번째 행 삭제
df = df.drop(df.index[0])

#삭제해서 인덱스 행이 1부터 시작하여 다시 그것을 재정렬 해주기 위해 행번호 초기화 후 다시 재정의
df=df.reset_index(drop=True)
df

id diagnosis radius_mean texture_mean perimeter_mean area_mean  \
0    DonorA_0001         1       17.99        10.38          122.8      1001   
1    DonorA_0002         1       20.57        17.77          132.9      1326   
2    DonorA_0003         1       19.69        21.25            130      1203   
3    DonorA_0004         1       11.42        20.38          77.58     386.1   
4    DonorA_0005         1       20.29        14.34          135.1      1297   
..           ...       ...         ...          ...            ...       ...   
564  DonorA_0565         1       21.56        22.39            142      1479   
565  DonorA_0566         1       20.13        28.25          131.2      1261   
566  DonorA_0567         1        16.6        28.08          108.3     858.1   
567  DonorA_0568         1        20.6        29.33          140.1      1265   
568  DonorA_0569         0        7.76        24.54          47.92       181   

    smoothness_mean compactness_mean concavity_mean concave points_mean  ...  \
0            0.1184           0.2776         0.3001              0.1471  ...   
1           0.08474          0.07864         0.0869             0.07017  ...   
2            0.1096           0.1599         0.1974              0.1279  ...   
3            0.1425           0.2839         0.2414              0.1052  ...   
4            0.1003           0.1328          0.198              0.1043  ...   
..              ...              ...            ...                 ...  ...   
564           0.111           0.1159         0.2439              0.1389  ...   
565          0.0978           0.1034          0.144             0.09791  ...   
566         0.08455           0.1023        0.09251             0.05302  ...   
567          0.1178            0.277         0.3514               0.152  ...   
568         0.05263          0.04362              0                   0  ...   

    radius_worst texture_worst perimeter_worst area_worst smoothness_worst  \
0          25.38         17.33           184.6       2019           0.1622   
1          24.99         23.41           158.8       1956           0.1238   
2          23.57         25.53           152.5       1709           0.1444   
3          14.91          26.5           98.87      567.7           0.2098   
4          22.54         16.67           152.2       1575           0.1374   
..           ...           ...             ...        ...              ...   
564        25.45          26.4           166.1       2027            0.141   
565        23.69         38.25             155       1731           0.1166   
566        18.98         34.12           126.7       1124           0.1139   
567        25.74         39.42           184.6       1821            0.165   
568        9.456         30.37           59.16      268.6          0.08996   

    compactness_worst concavity_worst concave points_worst symmetry_worst  \
0              0.6656          0.7119               0.2654         0.4601   
1              0.1866          0.2416                0.186          0.275   
2              0.4245          0.4504                0.243         0.3613   
3              0.8663          0.6869               0.2575         0.6638   
4               0.205             0.4               0.1625         0.2364   
..                ...             ...                  ...            ...   
564            0.2113          0.4107               0.2216          0.206   
565            0.1922          0.3215               0.1628         0.2572   
566            0.3094          0.3403               0.1418         0.2218   
567            0.8681          0.9387                0.265         0.4087   
568           0.06444               0                    0         0.2871   

    fractal_dimension_worst  
0                    0.1189  
1                   0.08902  
2                   0.08758  
3                     0.173  
4                   0.07678  
..                      ...  
564                 

In [258]:
#열심히 컬럼명 적었습니다!
X = df[['radius_mean', 'texture_mean','perimeter_mean', 'area_mean','smoothness_mean','compactness_mean','concavity_mean','concave points_mean','symmetry_mean','fractal_dimension_mean','radius_se','texture_se','perimeter_se','area_se','smoothness_se','compactness_se','concavity_se','concave points_se','symmetry_se','fractal_dimension_se','radius_worst','texture_worst','perimeter_worst','area_worst','smoothness_worst','compactness_worst','concavity_worst','concave points_worst','symmetry_worst','fractal_dimension_worst']]

#암인지 아닌지 해당 결과가 적혀있는 column을 y에 넣습니다
y = df['diagnosis']

In [259]:
y

0      1
1      1
2      1
3      1
4      1
      ..
564    1
565    1
566    1
567    1
568    0
Name: diagnosis, Length: 569, dtype: object

테스트 데이터를 분할합니다(일단 train 80 : test 20 으로 진행하겠습니다)

In [260]:
#데이터 분할 작업...
X_train, X_test, y_train, y_test  = train_test_split(X, y, test_size = 0.2)

랜덤 포레스트 모델을 이용한 데이터 학습

In [261]:
#랜덤포레스트 모델 선언!
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [262]:
#트리 개수는 일단 100으로 하였습니다
#확실한 측정을 위해 랜덤 요소는 0으로 맞추었습니다.
rf_model=RandomForestRegressor(n_estimators=100,random_state=0)
rf_model.fit(X_train,y_train)

RandomForestRegressor(random_state=0)

In [263]:
#랜덤포레스트 학습 완료된 모델을 이용하여 X_test 데이터를 넣어서 예측 시작!
rf_predict=rf_model.predict(X_test)

In [264]:
rf_predict

array([1.  , 1.  , 0.  , 0.89, 0.2 , 0.09, 0.  , 0.  , 0.4 , 0.  , 1.  ,
       0.96, 0.  , 0.83, 0.  , 1.  , 0.  , 1.  , 0.  , 1.  , 0.  , 1.  ,
       0.  , 0.04, 0.  , 0.  , 0.  , 0.56, 0.72, 0.66, 0.97, 0.  , 0.  ,
       0.  , 0.02, 0.67, 0.  , 0.  , 0.18, 0.99, 0.35, 1.  , 0.98, 0.82,
       0.  , 0.98, 0.78, 0.33, 0.  , 0.  , 0.  , 0.99, 0.97, 1.  , 0.01,
       0.  , 0.31, 0.  , 1.  , 0.01, 0.02, 0.  , 0.28, 0.  , 0.91, 0.  ,
       1.  , 0.99, 0.75, 0.  , 0.47, 0.97, 0.  , 0.  , 0.02, 1.  , 1.  ,
       0.  , 1.  , 1.  , 0.  , 1.  , 0.  , 0.  , 1.  , 0.02, 0.  , 0.  ,
       1.  , 0.43, 0.6 , 1.  , 0.  , 0.56, 0.  , 0.05, 0.99, 0.03, 0.6 ,
       0.96, 1.  , 0.  , 0.  , 0.  , 0.31, 0.44, 0.  , 0.  , 0.  , 1.  ,
       0.57, 1.  , 0.  , 0.  ])

In [265]:
#분류 모델은 정확하게 나뉘어져야 하다보니 0과 1로 변환하는 작업을 거쳤습니다.
#일반적으로 Image Detect할 때도 예측 수치가 0.5 넘는 것은 감지하여 감지된 객체의 label을 그리는 것처럼 이것 또한 동일하다고 생각하여 아래와 같이 진행하였습니다.

# 차원 펴주기
temp_pred = rf_predict.flatten()

#저는 일단 0.5보다크면 1(암이 있다), 작으면 0(암이 없다) 이렇게 진행했습니다.
rf_pre_set = np.where(temp_pred > 0.5, 1 , 0) 

In [266]:
rf_pre_set

array([1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0])

In [267]:
#타입이 안맞아서 오류가 나다보니 일단 타입을 동일하게 맞추었습니다.
y_test=y_test.astype(rf_pre_set.dtype)

In [268]:
#잘 타입 동일하게 바뀌었는지 확인위한 코드
y_test

75     1
323    1
333    0
321    1
255    1
      ..
257    1
484    0
129    1
150    0
427    0
Name: diagnosis, Length: 114, dtype: int64

In [269]:
#각 import 한 분류 평가 방법으로 진행
rf_accuracy = accuracy_score(y_test, rf_pre_set)
rf_precision = precision_score(y_test, rf_pre_set)
rf_recall = recall_score(y_test,rf_pre_set)
rf_f1= f1_score(y_test,rf_pre_set)
rf_roc= roc_auc_score(y_test,rf_pre_set)

In [270]:
#각 수치 정보들이 들어있는 값 출력
print("Accuracy=> ",rf_accuracy)
print("Precision=> ",rf_precision)
print("Recall=> ",rf_recall)
print("F1=> ",rf_f1)
print("AUC=> ",rf_roc)

Accuracy=>  0.956140350877193
Precision=>  0.9574468085106383
Recall=>  0.9375
F1=>  0.9473684210526315
AUC=>  0.9535984848484849


의사 결정 트리 모델을 이용한 데이터 학습

In [271]:
#의사 결정 트리 모델 불러오기!
from sklearn.tree import DecisionTreeClassifier

In [272]:
#확실한 측정을 위해 랜덤 요소는 0으로 하였습니다.
dt_model=DecisionTreeClassifier(random_state=0)

#그리고 의사결정트리 모델로 학습 진행!
dt_model.fit(X_train,y_train)

DecisionTreeClassifier(random_state=0)

In [273]:
#X_test에 있는 데이터들을 예측합니다.
dt_predict=dt_model.predict(X_test)

In [274]:
dt_predict

array(['1', '1', '0', '1', '0', '0', '0', '0', '1', '0', '1', '1', '0',
       '1', '0', '1', '0', '1', '0', '1', '0', '1', '0', '0', '0', '0',
       '0', '0', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0',
       '1', '1', '1', '1', '1', '0', '1', '1', '0', '0', '0', '0', '1',
       '1', '1', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '1',
       '0', '1', '1', '1', '0', '1', '1', '0', '0', '0', '1', '1', '0',
       '1', '1', '0', '1', '0', '0', '1', '0', '0', '0', '1', '0', '0',
       '1', '0', '1', '0', '0', '1', '0', '0', '1', '1', '0', '0', '0',
       '0', '1', '0', '0', '0', '1', '1', '1', '0', '0'], dtype=object)

In [275]:
#타입이 안맞아서 오류가 나다보니 일단 타입을 동일하게 맞추었습니다.
#이거는 모델 결과가 보니까 ' ' 이런 형식으로 나오길래 y_test에 있는 형식과 동일하게 얘를 맞춰주었습니다.
dt_predict=dt_predict.astype(y_test.dtype)

In [276]:
dt_predict

array([1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0])

In [277]:
#각 import 한 분류 평가 방법으로 진행
dt_accuracy = accuracy_score(y_test, dt_predict)
dt_precision = precision_score(y_test, dt_predict)
dt_recall = recall_score(y_test,dt_predict)
dt_f1= f1_score(y_test,dt_predict)
dt_roc= roc_auc_score(y_test,dt_predict)

In [278]:
#각 수치 정보들이 들어있는 값 출력
print("Accuracy=> ",dt_accuracy)
print("Precision=> ",dt_precision)
print("Recall=> ",dt_recall)
print("F1=> ",dt_f1)
print("AUC=> ",dt_roc)

Accuracy=>  0.9122807017543859
Precision=>  0.9130434782608695
Recall=>  0.875
F1=>  0.8936170212765957
AUC=>  0.9071969696969697


최종 두 모델의 분류 평가 결과 출력

In [279]:
print("Random Forest")
print("- Accuracy=> ",rf_accuracy)
print("- Precision=> ",rf_precision)
print("- Recall=> ",rf_recall)
print("- F1-score=> ",rf_f1)
print("- AUC=> ",rf_roc)

print("\n\n")

print("Decision Tree")
print("- Accuracy=> ",dt_accuracy)
print("- Precision=> ",dt_precision)
print("- Recall=> ",dt_recall)
print("- F1-score=> ",dt_f1)
print("- AUC=> ",dt_roc)


Random Forest
- Accuracy=>  0.956140350877193
- Precision=>  0.9574468085106383
- Recall=>  0.9375
- F1-score=>  0.9473684210526315
- AUC=>  0.9535984848484849



Decision Tree
- Accuracy=>  0.9122807017543859
- Precision=>  0.9130434782608695
- Recall=>  0.875
- F1-score=>  0.8936170212765957
- AUC=>  0.9071969696969697
